[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
runOnSave = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
postScriptGC = true

[client]
showErrorDetails = true
disconnectSlowClients = true

[logger]
level = "warning"
